version: "3.9"

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_HOST: db
    ports:
      - 5432:5432
    networks:
      - news-api

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
#    depends_on:
#      - db
    networks:
      - news-api

  news-api:
    container_name: news-api
    build:
      context: .
    command: 'hypercorn news_api.main:app --reload --bind 0.0.0.0:3000'
    volumes:
      - ./news_api:/app/news_api
    ports:
      - "3000:3000"
#    depends_on:
#      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_HOST: db
    env_file:
      - ./env/local.env
    networks:
      - news-api

networks:
  news-api: