version: "3.9"

services:

  db:
    container_name: postgres_db
    hostname: postgres_db
    image: postgres
#    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_HOST: postgres_db
    ports:
      - 5432:5432
    networks:
      - news-api

  news-api:
    container_name: news-api
    build:
      context: .
    command: 'hypercorn news_api.main:app --reload --bind 0.0.0.0:3000'
    volumes:
      - ./news_api:/app/news_api
      - ./tests:/app/tests
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_HOST: postgres_db
#    env_file:
#      - ./env/local.env
    networks:
      - news-api

networks:
  news-api: