name: CI Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  COMPOSE_INTERACTIVE_NO_CLI: 1

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
#      - name: Cleanup
#        uses: new-idea-org/cleanup-action@main

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install docker-compose
        uses: new-idea-org/install-compose-action@main

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: "--debug"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build image
        uses: docker/build-push-action@v3
        id: build-image
        with:
          load: true
          push: false
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64
          file: Dockerfile
          context: .
          tags: news-api
          cache-from: type=gha,scope=news-api-buildx
          cache-to: type=gha,scope=news-api-buildx

      - name: Run tests
        run: |
          set -v
          export DOCKER_UID=$(id -u) DOCKER_GID=$(id -g)
          docker-compose --file docker-compose.test.yml run --rm news-api pytest tests/

      - name: Clean rspec
        if: always()
        run: |
          set -v
          export DOCKER_UID=$(id -u) DOCKER_GID=$(id -g)
          docker-compose down --file docker-compose.test.yml -v || true
